!pragma teoz true

participant App
participant Intervall

App -> Intervall: setPeriod(1000)
|||
{start} App -> Intervall: begin

App -> App: doSomething

App -> Intervall: wait

{end} App <-- Intervall

{start} <-> {end}: 1000 mS